[package]
name = "crosvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[profile.release]
lto = true
panic = 'abort'

[workspace]

[features]
plugin = ["plugin_proto", "crosvm_plugin", "protobuf"]

[dependencies]
arch = { path = "arch" }
devices = { path = "devices" }
device_manager = { path = "device_manager" }
io_jail = { path = "io_jail" }
kvm = { path = "kvm" }
kvm_sys = { path = "kvm_sys" }
sys_util = { path = "sys_util" }
kernel_cmdline = { path = "kernel_cmdline" }
kernel_loader = { path = "kernel_loader" }
libc = "=0.2.40"
byteorder = "=1.1.0"
net_util = { path = "net_util" }
vhost = { path = "vhost" }
vm = { path = "vm" }
vm_control = { path = "vm_control" }
data_model = { path = "data_model" }
qcow = { path = "qcow" }
plugin_proto = { path = "plugin_proto", optional = true }
crosvm_plugin = { path = "crosvm_plugin", optional = true }
protobuf = { version = "=1.4.3", optional = true }
qcow_utils = { path = "qcow_utils" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { path = "x86_64" }

[dev-dependencies]
rand = "=0.3.20"
sys_util = { path = "sys_util" }
